POST http://192.168.10.100:30300/api/users/ HTTP/1.1
Content-Type: application/json

{
    "email": "nguyenhongthai@gmail.com",
    "name": "nguyenhongthai",
    "password": "Sinhdeptrai123",
    "phone": "0373418673"
}
###
GET  http://192.168.10.100:30300/ HTTP/1.1

###
POST http://192.168.10.100:30300/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "nguyenhongthai@gmail.com",
    "password": "Sinhdeptrai123"
}
###
POST http://192.168.10.100:30300/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "sinhvua@gmail.com",
    "password": "Sinhlolfo3123"
}
###
POST http://192.168.10.100:30300/api/stations/ HTTP/1.1
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYWJlYTViOGU4ZDFmNWRiNTBhNzg4OCIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY1NTQzNTMyNiwiZXhwIjoxNjU1NjA4MTI2fQ.OfVIWLjeh9kOtSGccqAfr_9tuT99X-MtwzD56rehuZY"

{
    "name": "ĐH TDTT",
    "description": "Đại học thể dục thể thao",
    "latitude": "10.871608",
    "longitude": "106.79662",
    "ip": "127.0.0.5"
}

###
POST http://192.168.10.100:30300/api/bikes/ HTTP/1.1
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYWJlYTViOGU4ZDFmNWRiNTBhNzg4OCIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY1NTQzNTMyNiwiZXhwIjoxNjU1NjA4MTI2fQ.OfVIWLjeh9kOtSGccqAfr_9tuT99X-MtwzD56rehuZY"

{
  
}
