apiVersion: apps/v1
kind: Deployment
metadata:
  name: bike_rental_api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bike_rental_api
  template:
    metadata:
      labels:
        app: bike_rental_api
    spec:
      containers:
      - name: api
        image: dongsinhho/bikeRentalApi:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
