apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bike_rental_api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bike_rental_api
  maxReplicas: 5
  minReplicas: 3
  targetCPUUtilizationPercentage: 80